# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

# Self-hosted runner labels (if using custom runners)
self-hosted-runner:
  labels: []

# Custom configuration variables
config-variables: []

# Disable shellcheck by setting empty path
# This prevents style warnings like SC2129 from failing the build
shellcheck:
  # Setting empty path disables shellcheck integration
  # Alternatively, you can set the path to a non-existent binary
  path: ""
