# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

# Self-hosted runner labels (if using custom runners)
self-hosted-runner:
  labels: []

# Custom configuration variables
config-variables: []

# Disable shellcheck integration to avoid info-level warnings
# These are style suggestions, not errors
shellcheck:
  enable: false
