# =============================================================================
# Fly.io Deployment Template
# =============================================================================
# Template for deploying backend applications to Fly.io.
# Copy to your repository's .github/workflows/ directory.
#
# Required secrets:
#   - FLY_API_TOKEN: Your Fly.io API token (generate at https://fly.io/user/personal_access_tokens)
#
# Optional secrets:
#   - DEPLOY_ENV_VARS: JSON object with environment variables for the app
#     Example: {"DATABASE_URL": "postgres://...", "REDIS_URL": "redis://..."}
# =============================================================================

name: Deploy to Fly.io

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  FLY_APP_NAME: ${{ github.event.repository.name }}

jobs:
  # Run quality checks first
  quality:
    name: Quality Checks
    uses: arrotech-solutions/arrotech-solutions-actions/.github/workflows/ci-code-quality.yml@main
    with:
      language: 'node'  # Change to 'python' or 'go' based on your backend
      node-version: '20'

  # Security scanning
  security:
    name: Security Scan
    uses: arrotech-solutions/arrotech-solutions-actions/.github/workflows/ci-security-scan.yml@main
    with:
      enable-codeql: true
      enable-secret-scan: true
      enable-dependency-scan: true

  # Run tests
  test:
    name: Tests
    needs: quality
    uses: arrotech-solutions/arrotech-solutions-actions/.github/workflows/ci-test.yml@main
    with:
      language: 'node'  # Change to 'python' or 'go' based on your backend
      node-version: '20'
      coverage-threshold: 70

  # Deploy to staging on develop branch
  deploy-staging:
    name: Deploy to Staging
    needs: [test, security]
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    uses: arrotech-solutions/arrotech-solutions-actions/.github/workflows/cd-deploy.yml@main
    with:
      environment: 'staging'
      platform: 'flyio'
      flyio-app-name: '${{ github.event.repository.name }}-staging'
      flyio-region: 'lhr'  # London region - adjust as needed
      flyio-vm-size: 'shared-cpu-1x'
      flyio-vm-memory: 256
      flyio-min-machines: 1
      flyio-max-machines: 2
      wait-for-rollout: true
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      DEPLOY_ENV_VARS: ${{ secrets.STAGING_ENV_VARS }}

  # Deploy to production on main
  deploy-production:
    name: Deploy to Production
    needs: [test, security]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: arrotech-solutions/arrotech-solutions-actions/.github/workflows/cd-deploy.yml@main
    with:
      environment: 'production'
      platform: 'flyio'
      flyio-app-name: '${{ github.event.repository.name }}'
      flyio-region: 'lhr'  # London region - adjust as needed
      flyio-vm-size: 'shared-cpu-1x'
      flyio-vm-memory: 512
      flyio-min-machines: 2
      flyio-max-machines: 5
      flyio-ha: true
      wait-for-rollout: true
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      DEPLOY_ENV_VARS: ${{ secrets.PRODUCTION_ENV_VARS }}

  # Post-deployment health check
  health-check:
    name: Health Check
    needs: [deploy-staging, deploy-production]
    if: always() && (needs.deploy-staging.result == 'success' || needs.deploy-production.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Wait for deployment to stabilize
        run: sleep 30

      - name: Check staging health
        if: needs.deploy-staging.result == 'success'
        env:
          STAGING_URL: ${{ needs.deploy-staging.outputs.deployment-url }}
        run: |
          if [ -n "$STAGING_URL" ]; then
            echo "Checking health at $STAGING_URL/health"
            curl -f "$STAGING_URL/health" || echo "Health check endpoint not found or failed"
          fi

      - name: Check production health
        if: needs.deploy-production.result == 'success'
        env:
          PROD_URL: ${{ needs.deploy-production.outputs.deployment-url }}
        run: |
          if [ -n "$PROD_URL" ]; then
            echo "Checking health at $PROD_URL/health"
            curl -f "$PROD_URL/health" || echo "Health check endpoint not found or failed"
          fi

