# =============================================================================
# Vercel Deployment Template (Preview â†’ Test â†’ Promote Pattern)
# =============================================================================
# Template for deploying frontend applications to Vercel with proper CI gates.
# 
# This implements the recommended pattern:
#   1. Deploy to preview URL
#   2. Run tests against preview
#   3. Only promote to production if tests pass
#
# Copy to your repository's .github/workflows/ directory.
#
# Required secrets:
#   - VERCEL_TOKEN: Your Vercel API token
#
# Optional:
#   - VERCEL_ORG_ID and VERCEL_PROJECT_ID if not using `vercel link`
# =============================================================================

name: Deploy to Vercel

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  # ===========================================================================
  # Step 1: Code Quality Checks
  # ===========================================================================
  quality:
    name: Quality Checks
    uses: arrotech-solutions/arrotech-solutions-actions/.github/workflows/ci-code-quality.yml@main
    with:
      language: 'node'
      node-version: '20'
      prettier-check: true

  # ===========================================================================
  # Step 2: Deploy to Preview URL
  # ===========================================================================
  deploy-preview:
    name: Deploy Preview
    needs: quality
    uses: arrotech-solutions/arrotech-solutions-actions/.github/workflows/cd-deploy.yml@main
    with:
      environment: 'staging'
      platform: 'vercel'
      vercel-deploy-mode: 'preview'
      working-directory: '.'
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  # ===========================================================================
  # Step 3: Run Tests Against Preview
  # ===========================================================================
  test:
    name: Test Against Preview
    needs: deploy-preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        env:
          CI: true
        run: |
          # Detect test framework and run tests
          if grep -q '"vitest"' package.json 2>/dev/null; then
            npm test -- --run
          elif grep -q '"jest"' package.json 2>/dev/null; then
            npm test -- --watchAll=false
          else
            npm test || echo "No tests configured"
          fi

      - name: Run E2E tests against preview
        if: hashFiles('playwright.config.*') != '' || hashFiles('cypress.config.*') != ''
        env:
          PREVIEW_URL: ${{ needs.deploy-preview.outputs.preview-url }}
        run: |
          echo "Running E2E tests against: $PREVIEW_URL"
          
          if [ -f "playwright.config.ts" ] || [ -f "playwright.config.js" ]; then
            npx playwright install --with-deps
            npx playwright test --base-url="$PREVIEW_URL"
          elif [ -f "cypress.config.ts" ] || [ -f "cypress.config.js" ]; then
            npx cypress run --config baseUrl="$PREVIEW_URL"
          fi

      - name: Preview URL Summary
        env:
          PREVIEW_URL: ${{ needs.deploy-preview.outputs.preview-url }}
        run: |
          {
            echo "## ðŸ” Preview Deployment"
            echo ""
            echo "**Preview URL:** $PREVIEW_URL"
            echo ""
            echo "Tests have been run against this preview deployment."
          } >> "$GITHUB_STEP_SUMMARY"

  # ===========================================================================
  # Step 4: Promote to Production (main branch only, after tests pass)
  # ===========================================================================
  promote-production:
    name: Promote to Production
    needs: [deploy-preview, test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: arrotech-solutions/arrotech-solutions-actions/.github/workflows/cd-deploy.yml@main
    with:
      environment: 'production'
      platform: 'vercel'
      vercel-deploy-mode: 'promote'
      vercel-deployment-url: ${{ needs.deploy-preview.outputs.preview-url }}
      working-directory: '.'
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  # ===========================================================================
  # PR Preview Comment
  # ===========================================================================
  pr-comment:
    name: Comment Preview URL
    needs: [deploy-preview, test]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment preview URL on PR
        uses: actions/github-script@v7
        env:
          PREVIEW_URL: ${{ needs.deploy-preview.outputs.preview-url }}
        with:
          script: |
            const previewUrl = process.env.PREVIEW_URL;
            const body = `## ðŸš€ Preview Deployment Ready!

            | Environment | URL |
            |-------------|-----|
            | Preview | ${previewUrl} |

            **Status:** âœ… Tests passed against preview

            This preview will be promoted to production when merged to \`main\`.`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
